# Import required libraries
library(shiny)
library(igraph)
library(networkD3)
library(network)
#library(ndtv)
library(htmlwidgets)
library(shinyBS)
library(intergraph)
library(infection.graph)
#library(animation)
library(htmltools)
library(ggplot2)
library(shinycssloaders)
library(shinyWidgets)
#library(knitr)
library(scales)
library(dplyr)
set.seed(4321)

# Import custom modules
source("./Code/ppeInfect_Module.R")
source("./Code/PPE_Module.R")
source("./Code/testingModule.R")
source("./Code/leaveModule.R")